version: '2'
services:
  pec-app:
    image: doug260188/debina:latest
    restart: always
    volumes:
      - ./:/pec-docker/
    ports:
      - 8000:8082
    stdin_open: true
    tty: true
    entrypoint:
      - bash
      - "entrypoint.sh"
    working_dir: /pec-docker/
    mem_limit: 2g

